#!/usr/bin/env node
// Assembles the engine. The Workflow runtime takes ONE self-contained script (no
// imports, a top-level `return`, `export const meta` first), and install.sh copies one
// file — so the engine is developed as the parts under src/ and built into
// workflows/build-verify-patch.js, which stays committed: a box without node installs it
// as it is. The parts are plain script fragments in one scope, concatenated in name
// order; a `const` in one part is visible to every part after it, and a function
// declaration to every part (hoisting holds across the whole script).
//
//   node build.js            # write workflows/build-verify-patch.js from src/
//   node build.js --check    # exit 1 if the committed engine differs from what src/ builds
'use strict'
const fs = require('fs')
const path = require('path')

const HERE = __dirname
const SRC_DIR = path.join(HERE, 'src')
const OUT = path.join(HERE, 'workflows', 'build-verify-patch.js')
const REL = (p) => path.relative(HERE, p).split(path.sep).join('/')

function parts() {
  const names = fs.readdirSync(SRC_DIR).filter((f) => /^\d\d-[\w-]+\.js$/.test(f)).sort()
  if (!names.length) throw new Error('no parts in ' + REL(SRC_DIR))
  if (!/^00-meta\.js$/.test(names[0])) throw new Error('the first part must be 00-meta.js so `export const meta` leads the script')
  return names.map((name) => ({ name, text: fs.readFileSync(path.join(SRC_DIR, name), 'utf8') }))
}

function banner(name) {
  const line = '// ' + '='.repeat(75)
  return [line, '// ' + REL(path.join(SRC_DIR, name)), line].join('\n')
}

function assemble() {
  const [meta, ...rest] = parts()
  const out = [
    meta.text.trim(),
    '',
    '// GENERATED by build.js from src/*.js — do not edit this file. Edit the part named in',
    '// the marker above each section, then run `node build.js`; check.sh fails when this',
    '// file is stale.',
  ]
  for (const p of rest) {
    out.push('', banner(p.name), p.text.trim())
  }
  return out.join('\n') + '\n'
}

function main(argv) {
  const built = assemble()
  if (argv.includes('--check')) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
    if (current !== built) {
      console.error(REL(OUT) + ' is stale: src/ has changed. Run `node build.js` and commit the result.')
      process.exit(1)
    }
    console.log(REL(OUT) + ' is up to date with src/')
    return
  }
  fs.writeFileSync(OUT, built)
  console.log('wrote ' + REL(OUT) + ' (' + built.split('\n').length + ' lines from ' + parts().length + ' parts)')
}

if (require.main === module) main(process.argv.slice(2))
module.exports = { assemble }
